//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketsBought
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string buyerPhone { get; set; }
        public string buyerAddress { get; set; }
        public int totalAdult { get; set; }
        public int totalChildren { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public string eventDescription { get; set; }
        public System.DateTime eventStartDate { get; set; }
    }
}
